global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8079"]

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8081"]

  - job_name: restaurant-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["restaurant-service:8082"]

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["order-service:8083"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8084"]

  - job_name: delivery-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["delivery-service:8086"]

