server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:fooddb}
    username: ${DB_USER:food}
    password: ${DB_PASSWORD:food}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-discovery:8761/eureka/}
